FROM golang:1.24-alpine

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

ENTRYPOINT ["CompileDaemon", "--build=go build -o main ./cmd", "--command=./main"]
