services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - ${PWD}/.env:/app/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SESSION_KEY: ${SESSION_KEY}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    env_file: .env
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:

networks:
  backend:
    driver: bridge
