// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"ppgroup.i0sys.com/ent/migrate"
	"github.com/google/uuid"

	"ppgroup.i0sys.com/ent/listing"
	"ppgroup.i0sys.com/ent/realtor"
	"ppgroup.i0sys.com/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Listing is the client for interacting with the Listing builders.
	Listing *ListingClient
	// Realtor is the client for interacting with the Realtor builders.
	Realtor *RealtorClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Listing = NewListingClient(c.config)
	c.Realtor = NewRealtorClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Listing: NewListingClient(cfg),
		Realtor: NewRealtorClient(cfg),
		User:    NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Listing: NewListingClient(cfg),
		Realtor: NewRealtorClient(cfg),
		User:    NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Listing.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Listing.Use(hooks...)
	c.Realtor.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Listing.Intercept(interceptors...)
	c.Realtor.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ListingMutation:
		return c.Listing.mutate(ctx, m)
	case *RealtorMutation:
		return c.Realtor.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ListingClient is a client for the Listing schema.
type ListingClient struct {
	config
}

// NewListingClient returns a client for the Listing from the given config.
func NewListingClient(c config) *ListingClient {
	return &ListingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `listing.Hooks(f(g(h())))`.
func (c *ListingClient) Use(hooks ...Hook) {
	c.hooks.Listing = append(c.hooks.Listing, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `listing.Intercept(f(g(h())))`.
func (c *ListingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Listing = append(c.inters.Listing, interceptors...)
}

// Create returns a builder for creating a Listing entity.
func (c *ListingClient) Create() *ListingCreate {
	mutation := newListingMutation(c.config, OpCreate)
	return &ListingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Listing entities.
func (c *ListingClient) CreateBulk(builders ...*ListingCreate) *ListingCreateBulk {
	return &ListingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ListingClient) MapCreateBulk(slice any, setFunc func(*ListingCreate, int)) *ListingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ListingCreateBulk{err: fmt.Errorf("calling to ListingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ListingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ListingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Listing.
func (c *ListingClient) Update() *ListingUpdate {
	mutation := newListingMutation(c.config, OpUpdate)
	return &ListingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ListingClient) UpdateOne(l *Listing) *ListingUpdateOne {
	mutation := newListingMutation(c.config, OpUpdateOne, withListing(l))
	return &ListingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ListingClient) UpdateOneID(id uuid.UUID) *ListingUpdateOne {
	mutation := newListingMutation(c.config, OpUpdateOne, withListingID(id))
	return &ListingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Listing.
func (c *ListingClient) Delete() *ListingDelete {
	mutation := newListingMutation(c.config, OpDelete)
	return &ListingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ListingClient) DeleteOne(l *Listing) *ListingDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ListingClient) DeleteOneID(id uuid.UUID) *ListingDeleteOne {
	builder := c.Delete().Where(listing.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ListingDeleteOne{builder}
}

// Query returns a query builder for Listing.
func (c *ListingClient) Query() *ListingQuery {
	return &ListingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeListing},
		inters: c.Interceptors(),
	}
}

// Get returns a Listing entity by its id.
func (c *ListingClient) Get(ctx context.Context, id uuid.UUID) (*Listing, error) {
	return c.Query().Where(listing.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ListingClient) GetX(ctx context.Context, id uuid.UUID) *Listing {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRealtor queries the realtor edge of a Listing.
func (c *ListingClient) QueryRealtor(l *Listing) *RealtorQuery {
	query := (&RealtorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := l.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(listing.Table, listing.FieldID, id),
			sqlgraph.To(realtor.Table, realtor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, listing.RealtorTable, listing.RealtorColumn),
		)
		fromV = sqlgraph.Neighbors(l.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ListingClient) Hooks() []Hook {
	return c.hooks.Listing
}

// Interceptors returns the client interceptors.
func (c *ListingClient) Interceptors() []Interceptor {
	return c.inters.Listing
}

func (c *ListingClient) mutate(ctx context.Context, m *ListingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ListingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ListingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ListingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ListingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Listing mutation op: %q", m.Op())
	}
}

// RealtorClient is a client for the Realtor schema.
type RealtorClient struct {
	config
}

// NewRealtorClient returns a client for the Realtor from the given config.
func NewRealtorClient(c config) *RealtorClient {
	return &RealtorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `realtor.Hooks(f(g(h())))`.
func (c *RealtorClient) Use(hooks ...Hook) {
	c.hooks.Realtor = append(c.hooks.Realtor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `realtor.Intercept(f(g(h())))`.
func (c *RealtorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Realtor = append(c.inters.Realtor, interceptors...)
}

// Create returns a builder for creating a Realtor entity.
func (c *RealtorClient) Create() *RealtorCreate {
	mutation := newRealtorMutation(c.config, OpCreate)
	return &RealtorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Realtor entities.
func (c *RealtorClient) CreateBulk(builders ...*RealtorCreate) *RealtorCreateBulk {
	return &RealtorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RealtorClient) MapCreateBulk(slice any, setFunc func(*RealtorCreate, int)) *RealtorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RealtorCreateBulk{err: fmt.Errorf("calling to RealtorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RealtorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RealtorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Realtor.
func (c *RealtorClient) Update() *RealtorUpdate {
	mutation := newRealtorMutation(c.config, OpUpdate)
	return &RealtorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RealtorClient) UpdateOne(r *Realtor) *RealtorUpdateOne {
	mutation := newRealtorMutation(c.config, OpUpdateOne, withRealtor(r))
	return &RealtorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RealtorClient) UpdateOneID(id uuid.UUID) *RealtorUpdateOne {
	mutation := newRealtorMutation(c.config, OpUpdateOne, withRealtorID(id))
	return &RealtorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Realtor.
func (c *RealtorClient) Delete() *RealtorDelete {
	mutation := newRealtorMutation(c.config, OpDelete)
	return &RealtorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RealtorClient) DeleteOne(r *Realtor) *RealtorDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RealtorClient) DeleteOneID(id uuid.UUID) *RealtorDeleteOne {
	builder := c.Delete().Where(realtor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RealtorDeleteOne{builder}
}

// Query returns a query builder for Realtor.
func (c *RealtorClient) Query() *RealtorQuery {
	return &RealtorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRealtor},
		inters: c.Interceptors(),
	}
}

// Get returns a Realtor entity by its id.
func (c *RealtorClient) Get(ctx context.Context, id uuid.UUID) (*Realtor, error) {
	return c.Query().Where(realtor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RealtorClient) GetX(ctx context.Context, id uuid.UUID) *Realtor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryListings queries the listings edge of a Realtor.
func (c *RealtorClient) QueryListings(r *Realtor) *ListingQuery {
	query := (&ListingClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(realtor.Table, realtor.FieldID, id),
			sqlgraph.To(listing.Table, listing.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, realtor.ListingsTable, realtor.ListingsColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RealtorClient) Hooks() []Hook {
	return c.hooks.Realtor
}

// Interceptors returns the client interceptors.
func (c *RealtorClient) Interceptors() []Interceptor {
	return c.inters.Realtor
}

func (c *RealtorClient) mutate(ctx context.Context, m *RealtorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RealtorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RealtorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RealtorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RealtorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Realtor mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Listing, Realtor, User []ent.Hook
	}
	inters struct {
		Listing, Realtor, User []ent.Interceptor
	}
)
