// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"ppgroup.m0chi.com/ent/listing"
	"ppgroup.m0chi.com/ent/predicate"
	"ppgroup.m0chi.com/ent/realtor"
)

// RealtorQuery is the builder for querying Realtor entities.
type RealtorQuery struct {
	config
	ctx          *QueryContext
	order        []realtor.OrderOption
	inters       []Interceptor
	predicates   []predicate.Realtor
	withListings *ListingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RealtorQuery builder.
func (rq *RealtorQuery) Where(ps ...predicate.Realtor) *RealtorQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RealtorQuery) Limit(limit int) *RealtorQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RealtorQuery) Offset(offset int) *RealtorQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RealtorQuery) Unique(unique bool) *RealtorQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RealtorQuery) Order(o ...realtor.OrderOption) *RealtorQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryListings chains the current query on the "listings" edge.
func (rq *RealtorQuery) QueryListings() *ListingQuery {
	query := (&ListingClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realtor.Table, realtor.FieldID, selector),
			sqlgraph.To(listing.Table, listing.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, realtor.ListingsTable, realtor.ListingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Realtor entity from the query.
// Returns a *NotFoundError when no Realtor was found.
func (rq *RealtorQuery) First(ctx context.Context) (*Realtor, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{realtor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RealtorQuery) FirstX(ctx context.Context) *Realtor {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Realtor ID from the query.
// Returns a *NotFoundError when no Realtor ID was found.
func (rq *RealtorQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{realtor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RealtorQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Realtor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Realtor entity is found.
// Returns a *NotFoundError when no Realtor entities are found.
func (rq *RealtorQuery) Only(ctx context.Context) (*Realtor, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{realtor.Label}
	default:
		return nil, &NotSingularError{realtor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RealtorQuery) OnlyX(ctx context.Context) *Realtor {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Realtor ID in the query.
// Returns a *NotSingularError when more than one Realtor ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RealtorQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{realtor.Label}
	default:
		err = &NotSingularError{realtor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RealtorQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Realtors.
func (rq *RealtorQuery) All(ctx context.Context) ([]*Realtor, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryAll)
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Realtor, *RealtorQuery]()
	return withInterceptors[[]*Realtor](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RealtorQuery) AllX(ctx context.Context) []*Realtor {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Realtor IDs.
func (rq *RealtorQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryIDs)
	if err = rq.Select(realtor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RealtorQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RealtorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryCount)
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RealtorQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RealtorQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RealtorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryExist)
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RealtorQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RealtorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RealtorQuery) Clone() *RealtorQuery {
	if rq == nil {
		return nil
	}
	return &RealtorQuery{
		config:       rq.config,
		ctx:          rq.ctx.Clone(),
		order:        append([]realtor.OrderOption{}, rq.order...),
		inters:       append([]Interceptor{}, rq.inters...),
		predicates:   append([]predicate.Realtor{}, rq.predicates...),
		withListings: rq.withListings.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithListings tells the query-builder to eager-load the nodes that are connected to
// the "listings" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RealtorQuery) WithListings(opts ...func(*ListingQuery)) *RealtorQuery {
	query := (&ListingClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withListings = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Realtor.Query().
//		GroupBy(realtor.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RealtorQuery) GroupBy(field string, fields ...string) *RealtorGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RealtorGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = realtor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.Realtor.Query().
//		Select(realtor.FieldCreateTime).
//		Scan(ctx, &v)
func (rq *RealtorQuery) Select(fields ...string) *RealtorSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RealtorSelect{RealtorQuery: rq}
	sbuild.label = realtor.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RealtorSelect configured with the given aggregations.
func (rq *RealtorQuery) Aggregate(fns ...AggregateFunc) *RealtorSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RealtorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !realtor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RealtorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Realtor, error) {
	var (
		nodes       = []*Realtor{}
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withListings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Realtor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Realtor{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withListings; query != nil {
		if err := rq.loadListings(ctx, query, nodes,
			func(n *Realtor) { n.Edges.Listings = []*Listing{} },
			func(n *Realtor, e *Listing) { n.Edges.Listings = append(n.Edges.Listings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RealtorQuery) loadListings(ctx context.Context, query *ListingQuery, nodes []*Realtor, init func(*Realtor), assign func(*Realtor, *Listing)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Realtor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(listing.FieldRealtorID)
	}
	query.Where(predicate.Listing(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realtor.ListingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealtorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "realtor_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *RealtorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RealtorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(realtor.Table, realtor.Columns, sqlgraph.NewFieldSpec(realtor.FieldID, field.TypeUUID))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, realtor.FieldID)
		for i := range fields {
			if fields[i] != realtor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RealtorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(realtor.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = realtor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RealtorGroupBy is the group-by builder for Realtor entities.
type RealtorGroupBy struct {
	selector
	build *RealtorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RealtorGroupBy) Aggregate(fns ...AggregateFunc) *RealtorGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RealtorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, ent.OpQueryGroupBy)
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealtorQuery, *RealtorGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RealtorGroupBy) sqlScan(ctx context.Context, root *RealtorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RealtorSelect is the builder for selecting fields of Realtor entities.
type RealtorSelect struct {
	*RealtorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RealtorSelect) Aggregate(fns ...AggregateFunc) *RealtorSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RealtorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, ent.OpQuerySelect)
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealtorQuery, *RealtorSelect](ctx, rs.RealtorQuery, rs, rs.inters, v)
}

func (rs *RealtorSelect) sqlScan(ctx context.Context, root *RealtorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
