// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Listing is the predicate function for listing builders.
type Listing func(*sql.Selector)

// Realtor is the predicate function for realtor builders.
type Realtor func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
